// Code generated by github.com/wubin1989/gen. DO NOT EDIT.
// Code generated by github.com/wubin1989/gen. DO NOT EDIT.
// Code generated by github.com/wubin1989/gen. DO NOT EDIT.

package model

import (
	"fmt"

	"github.com/go-cinderella/cinderella-engine/engine/config"
	"github.com/unionj-cloud/toolkit/stringutils"
)

//go:generate go-doudou name --file $GOFILE --case snake

// ActGeBytearray mapped from table <act_ge_bytearray>
type ActGeBytearray struct {
	ID_           string  `gorm:"column:ID_;type:varchar(64);primaryKey" json:"id_"`
	Rev_          *int32  `gorm:"column:REV_;type:integer" json:"rev_"`
	Name_         *string `gorm:"column:NAME_;type:varchar(255)" json:"name_"`
	DeploymentID_ *string `gorm:"column:DEPLOYMENT_ID_;type:varchar(64);index:act_idx_bytear_depl,priority:1" json:"deployment_id_"`
	Bytes_        *[]byte `gorm:"column:BYTES_;type:bytea" json:"bytes_"`
	Generated_    *bool   `gorm:"column:GENERATED_;type:boolean" json:"generated_"`
}

// TableName ActGeBytearray's table name
func (*ActGeBytearray) TableName() string {
	var TableNameActGeBytearray string

	if stringutils.IsNotEmpty(config.G_Config.Db.Name) {
		TableNameActGeBytearray = fmt.Sprintf("%s.act_ge_bytearray", config.G_Config.Db.Name)
	} else {
		TableNameActGeBytearray = "act_ge_bytearray"
	}

	return TableNameActGeBytearray
}
