// Code generated by github.com/wubin1989/gen. DO NOT EDIT.
// Code generated by github.com/wubin1989/gen. DO NOT EDIT.
// Code generated by github.com/wubin1989/gen. DO NOT EDIT.

package model

import (
	"fmt"

	"github.com/go-cinderella/cinderella-engine/engine/config"
	"github.com/unionj-cloud/toolkit/stringutils"
)

//go:generate go-doudou name --file $GOFILE --case snake

// ActReProcdef mapped from table <act_re_procdef>
type ActReProcdef struct {
	ID_                   string  `gorm:"column:ID_;type:varchar(64);primaryKey" json:"id_"`
	Rev_                  *int32  `gorm:"column:REV_;type:integer" json:"rev_"`
	Category_             *string `gorm:"column:CATEGORY_;type:varchar(255)" json:"category_"`
	Name_                 *string `gorm:"column:NAME_;type:varchar(255)" json:"name_"`
	Key_                  string  `gorm:"column:KEY_;type:varchar(255);not null" json:"key_"`
	Version_              int32   `gorm:"column:VERSION_;type:integer;not null" json:"version_"`
	DeploymentID_         *string `gorm:"column:DEPLOYMENT_ID_;type:varchar(64)" json:"deployment_id_"`
	ResourceName_         *string `gorm:"column:RESOURCE_NAME_;type:varchar(4000)" json:"resource_name_"`
	DgrmResourceName_     *string `gorm:"column:DGRM_RESOURCE_NAME_;type:varchar(4000)" json:"dgrm_resource_name_"`
	Description_          *string `gorm:"column:DESCRIPTION_;type:varchar(4000)" json:"description_"`
	HasStartFormKey_      *bool   `gorm:"column:HAS_START_FORM_KEY_;type:boolean" json:"has_start_form_key_"`
	HasGraphicalNotation_ *bool   `gorm:"column:HAS_GRAPHICAL_NOTATION_;type:boolean" json:"has_graphical_notation_"`
	SuspensionState_      *int32  `gorm:"column:SUSPENSION_STATE_;type:integer" json:"suspension_state_"`
	TenantID_             *string `gorm:"column:TENANT_ID_;type:varchar(255)" json:"tenant_id_"`
	DerivedFrom_          *string `gorm:"column:DERIVED_FROM_;type:varchar(64)" json:"derived_from_"`
	DerivedFromRoot_      *string `gorm:"column:DERIVED_FROM_ROOT_;type:varchar(64)" json:"derived_from_root_"`
	DerivedVersion_       *int32  `gorm:"column:DERIVED_VERSION_;type:integer;not null;default:0" json:"derived_version_"`
	EngineVersion_        *string `gorm:"column:ENGINE_VERSION_;type:varchar(255)" json:"engine_version_"`
	ProcessID_            string  `gorm:"column:process_id_;type:varchar(255)" json:"process_id_"`
}

// TableName ActReProcdef's table name
func (*ActReProcdef) TableName() string {
	var TableNameActReProcdef string

	if stringutils.IsNotEmpty(config.G_Config.Db.Name) {
		TableNameActReProcdef = fmt.Sprintf("%s.act_re_procdef", config.G_Config.Db.Name)
	} else {
		TableNameActReProcdef = "act_re_procdef"
	}

	return TableNameActReProcdef
}
