// Code generated by github.com/wubin1989/gen. DO NOT EDIT.
// Code generated by github.com/wubin1989/gen. DO NOT EDIT.
// Code generated by github.com/wubin1989/gen. DO NOT EDIT.

package model

import (
	"fmt"

	"github.com/go-cinderella/cinderella-engine/engine/config"
	"github.com/unionj-cloud/toolkit/stringutils"

	"time"
)

//go:generate go-doudou name --file $GOFILE --case snake

// ActHiIdentitylink mapped from table <act_hi_identitylink>
type ActHiIdentitylink struct {
	ID_                string     `gorm:"column:ID_;type:varchar(64);primaryKey" json:"id_"`
	GroupID_           *string    `gorm:"column:GROUP_ID_;type:varchar(255)" json:"group_id_"`
	Type_              *string    `gorm:"column:TYPE_;type:varchar(255)" json:"type_"`
	UserID_            *string    `gorm:"column:USER_ID_;type:varchar(255);index:act_idx_hi_ident_lnk_user,priority:1" json:"user_id_"`
	TaskID_            *string    `gorm:"column:TASK_ID_;type:varchar(64);index:act_idx_hi_ident_lnk_task,priority:1" json:"task_id_"`
	CreateTime_        *time.Time `gorm:"column:CREATE_TIME_;type:timestamp without time zone" json:"create_time_"`
	ProcInstID_        *string    `gorm:"column:PROC_INST_ID_;type:varchar(64);index:act_idx_hi_ident_lnk_procinst,priority:1" json:"proc_inst_id_"`
	ScopeID_           *string    `gorm:"column:SCOPE_ID_;type:varchar(255);index:act_idx_hi_ident_lnk_scope,priority:1" json:"scope_id_"`
	SubScopeID_        *string    `gorm:"column:SUB_SCOPE_ID_;type:varchar(255);index:act_idx_hi_ident_lnk_sub_scope,priority:1" json:"sub_scope_id_"`
	ScopeType_         *string    `gorm:"column:SCOPE_TYPE_;type:varchar(255);index:act_idx_hi_ident_lnk_scope,priority:2;index:act_idx_hi_ident_lnk_sub_scope,priority:2;index:act_idx_hi_ident_lnk_scope_def,priority:1" json:"scope_type_"`
	ScopeDefinitionID_ *string    `gorm:"column:SCOPE_DEFINITION_ID_;type:varchar(255);index:act_idx_hi_ident_lnk_scope_def,priority:2" json:"scope_definition_id_"`
}

// TableName ActHiIdentitylink's table name
func (*ActHiIdentitylink) TableName() string {
	var TableNameActHiIdentitylink string

	if stringutils.IsNotEmpty(config.G_Config.Db.Name) {
		TableNameActHiIdentitylink = fmt.Sprintf("%s.act_hi_identitylink", config.G_Config.Db.Name)
	} else {
		TableNameActHiIdentitylink = "act_hi_identitylink"
	}

	return TableNameActHiIdentitylink
}
